### ISSUE TITLE
Remove Added View

### ISSUE THREAD

**Issue by GauravCreed** [paulyung541/LaybelLayout#1]
Hi @paulyung541 

is it possible to remove all added view in LaybelLayout to add next items of lable, i will try to remove using this..

`laybel_layout.removeAllViewsInLayout();` **OR** `laybel_layout.removeAllViews();`

please help me to solve this issue..

Thanks..(_)

**Comment by paulyung541** [comment]
The LaybelLayout inherit the ViewGroup, you can try to use ViewGroup#removeAllViews() or ViewGroup#removeView(View) to do this.

**Comment by paulyung541** [comment]
The LaybelLayout inherit the ViewGroup, you can try to use ViewGroup#removeAllViews() or ViewGroup#removeView(View) to do this.

**Comment by GauravCreed** [comment]
Hi @paulyung541 

i tried as you say, but when i remove child from ViewGroup like 
`if (laybel_layout.getChildCount() > 0) {
	laybel_layout.removeAllViews();
}`

it remove all view from this LaybelLayout, and after i add some other view then it contain black space (Before delete view) and then add new view.

![Screenshot_1561463609](https://user-images.githubusercontent.com/13447384/60096275-238ab380-976e-11e9-9a94-6129422f9f4a.png)

how can i resolve this.;

**Comment by GauravCreed** [comment]
Hi @paulyung541 

i just added  NestedScrollView -> LaybelLayout
After i added edittext in LaybelLayout programmatically, then after i remove added edittext from LaybelLayout using laybelLayout.removeAllViewsInLayout() that time issue is generate this space is ramianing after remove all view.

can u pls help me to resolve this?
Thanks.
