### ISSUE TITLE
Child can be center horizontal?

### ISSUE THREAD

**Issue by Android234** [paulyung541/LaybelLayout#2]

**Comment by DevNigam** [comment]
I also require that.
can you give me a concept picture as you describe?

**Comment by EpariNigam** [comment]
![imageedit_2_8213212117](https://cloud.githubusercontent.com/assets/11530869/24946914/49cd1c06-1f82-11e7-9386-6170ce53ac94.jpg)


@paulyung541 Please check the image.

**Comment by paulyung541** [comment]
@EpariNigam I will add this soon.

**Comment by EpariNigam** [comment]
@paulyung541 Is it possible in the latest version?
